### PR TITLE
Add sessiontoken support

### PR DESCRIPTION
**Pull request by mirubiri**
Add support for session tokens: 
https://developers.google.com/places/web-service/autocomplete#session_tokens

### CODE REVIEW

**Comment by phuphighter** [comment]
Thanks @mirubiri!

**Comment by mirubiri** [comment]
@phuphighter You're welcome, time for a new release! ☺️

**Comment by phuphighter** [comment]
@mirubiri new version should be out there now!

**Comment by mirubiri** [comment]
@phuphighter thanks for the fast merge & gem update!

**Pull request merged**
